pragma solidity ^0.8.17;

import "forge-std/Script.sol";

contract NetexStack is Script {
  address WETH9_ADDRESS = vm.envAddress("WETH9");
  address CURRENCY_MANAGER_ADDRESS = vm.envAddress("CURRENCY_MANAGER");
  address EXECUTION_MANAGER_ADDRESS = vm.envAddress("EXECUTION_MANAGER");
  address ROYALITY_FEE_REGISTRY_ADDRESS = vm.envAddress("ROYALITY_FEE_REGISTRY");
  address ROYALITY_FEE_MANAGER_ADDRESS = vm.envAddress("ROYALITY_FEE_MANAGER");
  address NETEX_EXCHANGE_ADDRESS = vm.envAddress("NETEX_EXCHANGE");
  address TRANSFER_MANAGER_ERC721_ADDRESS = vm.envAddress("TRANSFER_MANAGER_ERC721");
  address TRANSFER_MANAGER_ERC1155_ADDRESS = vm.envAddress("TRANSFER_MANAGER_ERC1155");
  address TRANSFER_SELECTOR_NFT_ADDRESS = vm.envAddress("TRANSFER_SELECTOR_NFT");
  address STRATEGY_ANY_ITEM_FOR_FIXED_PRICE_ADDRESS = vm.envAddress("STRATEGY_ANY_ITEM_FOR_FIXED_PRICE");
  address STRATEGY_PRIVATE_SALE_ADDRESS = vm.envAddress("STRATEGY_PRIVATE_SALE");
  address STRATEGY_STANDART_SALE_FOR_FIXED_PRICE_ADDRESS = vm.envAddress("STRATEGY_STANDART_SALE_FOR_FIXED_PRICE");
}
